name: Code Test

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Code Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go LATEST
      run: |
        curl -fsSL https://raw.githubusercontent.com/capric98/myenv/master/Go/Linux/install.sh | bash

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: /usr/local/go/bin/go test ./...
